### ISSUE TITLE
Why the target in loss_contrast is 1?

### ISSUE THREAD

**Issue by hitlei** [tientrandinh/Revisiting-Reverse-Distillation#1]
![image](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/37055663/8de10077-8b6b-4d0a-8b66-8ae82d935acb)

to push away abnormal information from projected normal space, should target in this code be -1?

**Comment by tientrandinh** [comment]
Hi, You are correct that the 'target' should be -1; it was a typo during my code refactoring process. I have already updated it. The repository is gradually being cleaned and uploaded, as it has not been officially completed yet. Thank you so much for the prompt notice.
