### ISSUE TITLE
缺陷检测交流微信群，互相交流学习进步

### ISSUE THREAD

**Issue by RuojiWang** [tientrandinh/Revisiting-Reverse-Distillation#13]
缺陷检测交流微信群，互相交流学习进步

![20240108092627](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/3c0336a0-2e6e-4944-8e56-ff54f4535dd3)

**Comment by Sj-Yuan** [comment]
人家越南人也要拉进微信群是吧

**Comment by RuojiWang** [comment]
![微信图片_20240122140446](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/d1ee7600-bc7b-4a79-a077-fe8f4596751d)

**Comment by RuojiWang** [comment]
![微信图片_20240129140511](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/60a97af4-ce52-41b9-895a-7466cf138f84)

**Comment by gaobb** [comment]
二维码已过期，辛苦帮再更新一个，非常感谢！

**Comment by RuojiWang** [comment]
![微信图片_20240206092951](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/c67f3096-6898-4ee7-a4f0-eda87358d31e)

**Comment by RuojiWang** [comment]
> 二维码已过期，辛苦帮再更新一个，非常感谢！

已发

**Comment by RuojiWang** [comment]
![微信图片_20240219092628](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/9498fb98-1cd1-44e4-b4d3-385ff56ef0ee)

**Comment by RuojiWang** [comment]
![微信图片_20240227095422](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/18ccfa8d-62ab-4ca9-a988-6be52121ab2c)

**Comment by RuojiWang** [comment]
![微信图片_20240304120151](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/98fb8ffc-7a38-415f-9d86-a82f49b475eb)

**Comment by RuojiWang** [comment]
![微信图片_20240311093232](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/4339ba53-c0d1-4a2a-9c77-261fe6ac060e)

**Comment by RuojiWang** [comment]
![微信图片_20240319150100](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/8321fabd-7328-4dd2-82d0-15b82b73317e)

**Comment by RuojiWang** [comment]
![微信图片_20240325162932](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/9f035ea3-872c-4476-82ed-436176413970)

**Comment by RuojiWang** [comment]
![微信图片_20240401141650](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/967851df-9225-4599-8065-f62840831d87)

**Comment by tdh512194** [comment]
closed due to spam

**Comment by RuojiWang** [comment]
![微信图片_20240415165927](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/0cf1a940-1242-41eb-bd63-471d26d2f56d)

**Comment by RuojiWang** [comment]
![微信图片_20240506143808](https://github.com/tientrandinh/Revisiting-Reverse-Distillation/assets/14054362/1fdc16f4-c1a0-4a91-a32b-268fa720c73a)
