### ISSUE TITLE
why do you have multiple models?

### ISSUE THREAD

**Issue by Leminhhuy2386** [tientrandinh/Revisiting-Reverse-Distillation#14]
Thank you for your work!
There is a pre-trained model for every object, as you uploaded.
Don't you have a single model for all objects in the MVTecAD dataset?
The results in the paper are the single model or multiple models?

**Comment by tientrandinh** [comment]
Thanks for your question. This paper is about anomaly detection for one class at a time (one model for one class). Your question relates to another type of task: anomaly detection for multi-class classification, which is not our goal in this paper. This paper, https://arxiv.org/abs/2206.03687, might capture your interest.
