### ISSUE TITLE
When designing the loss_contrast，do we need to consider noise mask location information?

### ISSUE THREAD

**Issue by hitlei** [tientrandinh/Revisiting-Reverse-Distillation#5]
loss_contrast = self.contrast(noised_feature1.view(noised_feature1.shape[0], -1), normal_proj1.view(normal_proj1.shape[0], -1), target = target) + self.contrast(noised_feature2.view(noised_feature2.shape[0], -1), normal_proj2.view(normal_proj2.shape[0], -1), target = target) + self.contrast(noised_feature3.view(noised_feature3.shape[0], -1), normal_proj3.view(normal_proj3.shape[0], -1), target = target)

In this code, when using CosineEmbeddingLoss to push away normal and abnormal features, you did not use **noise mask** information.
I`m afraid this may causes the parts that are not noised to be pulled away, but in fact, they're all normal features.

**Comment by tdh512194** [comment]
@hitlei we are treating individual sample as an instance to be pushed away if it is abnormal by flattenning the feature maps for the cosine embdding loss. An alternative to flattenning could be using global average pooling. I think you made an interesting point where the constrative loss can be performed locally (pixel-wise) by leveraging the noise mask. However, it gets complicated as we are comparing latent features, not the original input. In the latent feature maps, each local pixel's receptive field expands as we go deeper, making the respective location of the noise mask boundary expands and eventually got covered by the whole spatial coordinate. Hence, we are choosing a more simpler way by contrasting the global features.
