### ISSUE TITLE
where is GLEAM in resnet.py

### ISSUE THREAD

**Issue by frankczh-123** [tientrandinh/Revisiting-Reverse-Distillation#8]
where is GLEAM in resnet.py

**Comment by tdh512194** [comment]
Thank you. We tried CBAM but did not used as commented out!

**Comment by tientrandinh** [comment]
Hello @frankczh-123, you can locate the CBAM block at line 320 in the resnet.py. We kept our code consistent with the baseline RD code. Although we are not utilizing CBAM in experiments, feel free to uncomment the CBAM block and play with it as needed in your own experiment.
